name: frontend
description: "Speed Dating App Frontend"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.0

  # Networking
  dio: ^5.5.0

  # Code Generation & Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Utilities
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  url_launcher: ^6.3.0

  # Icons
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^2.0.1
  cached_network_image: ^3.4.1
  socket_io_client: ^3.1.4
  record: ^6.2.0
  audioplayers: ^6.5.1
  permission_handler: ^12.0.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
